# Question 1

>>>

In [5]:
a = 0 

def b():
    global a  
    a = c(a)

def c(a):
    return a + 2

print(f"Initial value of a: {a}")  # Initial value of a is 0
b() # the first call to b()
print(f"Value of a after first b(): {a}")  # Value of a is now  2
b() # the second  call to b()
print(f"Value of a after second b(): {a}")  # Value of a is now 4
b() #  the third call to b()
print(f"Value of a after third b(): {a}")  # Value of a is now  6
print(f"Final value of a: {a}")  # Final value of a is  6

Initial value of a: 0
Value of a after first b(): 2
Value of a after second b(): 4
Value of a after third b(): 6
Final value of a: 6

# Question 1 : Explanation
the global variable 1 is set to 0
we have the b() function that is set to modify the global variable a by calling the function c(a), the function c(a) is to return a+2, each value called to b() updates the value of a base on the vale returned from c(a), afer each of the call to b() , we print the values of a to show the changes

# Question 2 :
dFunction fileLength(), given to you, takes the name of a file as input and returns
the length of the file:
>>> fileLength('midterm.py')
284
>>> fileLength('idterm.py')
Traceback (most recent call last):
File "<pyshell#34>", line 1, in <module>
 fileLength('idterm.py')
File "/Users/me/midterm.py", line 3, in fileLength
 infile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory:
'idterm.py'
As shown above, if the file cannot be found by the interpreter or if it cannot be read
as a text file, an exception will be raised. Modify function fileLength() so that a
friendly message is printed instead:
>>> fileLength('midterm.py')
358
>>> fileLength('idterm.py')
File idterm.py not found.term.py not found.

In [34]:
def fileLength(filename):
    try:
        with open(filename, 'r') as infile:  
            contents = infile.read()  
            print(len(contents))  
    except FileNotFoundError:
        print(f"File {filename} not found.")  
        
if __name__ == "__main__":
    
    file_path = r"C:\Users\user\Filelength.txt" 
    fileLength(file_path) 
    
 
    non_existing_file_path = r"C:\Users\user\idterm.py"  
    fileLength(non_existing_file_path)

123
File C:\Users\user\idterm.py not found.

# Question 3
Write a class named Marsupial that can be used as shown below:
>>> m = Marsupial()
>>> m.put_in_pouch('doll')
>>> m.put_in_pouch('firetruck')
>>> m.put_in_pouch('kitten')
>>> m.pouch_contents()
['doll', 'firetruck', 'ki
Now write a class named Kangaroo as a subclass of Marsupial that inherits all the
attributes of Marsupial and also:
a. extends the Marsupial __init__ constructor to take, as input, the
coordinates x and y of the Kangaroo object,
b. supports method jump that takes number values dx and dy as input and
moves the kangaroo by dx units along the x-axis and by dy units along the yaxis, and
c. overloads the __str__ operator so it behaves as shown below.
>>> k = Kangaroo(0,0)
>>> print(k)
I am a Kangaroo located at coordinates (0,0)
>>> k.put_in_pouch('doll')
>>> k.put_in_pouch('firetruck')
>>> k.put_in_pouch('kitten')
>>> k.pouch_contents()
['doll', 'firetruck', 'kitten']
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> print(k)
I am a Kangaroo located at coordinates (3,0)tten']

In [70]:
class Marsupial:
    def __init__(self):
        self.pouch = []
    def put_in_pouch(self, item):
        self.pouch.append(item)
    def pouch_contents(self):
        return self.pouch

class Kangaroo(Marsupial):
    def __init__(self, x, y):
        super().__init__() 
        self.x = x
        self.y = y
    def jump(self, dx, dy):
        self.x += dx
        self.y += dy
    def __str__(self):
        return f"I am a Kangaroo located at coordinates ({self.x},{self.y})"

if __name__ == "__main__":
    m = Marsupial()
    m.put_in_pouch('doll')
    m.put_in_pouch('firetruck')
    m.put_in_pouch('kitten')
    print(m.pouch_contents()) 

    k = Kangaroo(0, 0)
    print(k)
    k.put_in_pouch('doll')
    k.put_in_pouch('firetruck')
    k.put_in_pouch('kitten')
    print(k.pouch_contents()) 
    k.jump(1, 0)
    k.jump(1, 0)
    k.jump(1, 0)
    print('k')

['doll', 'firetruck', 'kitten']
I am a Kangaroo located at coordinates (0,0)
['doll', 'firetruck', 'kitten']
k I am a Kangaroo located at coordinates (3,0)

# Question 4

Write function collatz() that takes a positive integer x as input and prints the
Collatz sequence starting at x. A Collatz sequence is obtained by repeatedly applying
this rule to the previous number x in the sequence:
x = {
𝑥/2 𝑖𝑓 𝑥 𝑖𝑠 𝑒𝑣𝑒𝑛
3𝑥 + 1 𝑖𝑓 𝑥 𝑖𝑠 𝑜𝑑𝑑
Your function should stop when the sequence gets to number 1. Your
implementation must be recursive, without any
 >>> collatz(1)
1
>>> collatz(10)
10
5
16
8
4
2
1 loops.

In [52]:
def collatz(x):
    print(x)  
    if x == 1:  
        return
    elif x % 2 == 0:  
        collatz(x // 2)  
    else:  
        collatz(3 * x + 1) 
        
if __name__ == "__main__":
    print ("Collatz(1)")
    
    collatz(1)
    print() 
    print ("Collatz(10)")
    
    collatz(10)

Collatz(1)
1

Collatz(10)
10
5
16
8
4
2
1

# Question 5 
Write a recursive method binary() that takes a non-negative
integer n and prints the binary representation of integer n.
>>> binary(0)
0
>>> binary(1)
1
>>> binary(3)
11
>>> binary(9)
1001

In [56]:
def binary(n):
    if n > 1:  
        binary(n // 2) 
    print(n % 2, end='') 


if __name__ == "__main__":
    print("binary(0)")
    binary(0)  
    print()  
    print("binary(1)")
    binary(1)  
    print()  
    print("binary(3)")
    binary(3)
    print()  
    print("binary(9)")
    binary(9)  
    print()

binary(0)
0
binary(1)
1
binary(3)
11
binary(9)
1001

# Question 6

Implement a class named HeadingParser that can be used to parse an HTML
document, and retrieve and print all the headings in the document. You should
implement your class as a subclass of HTMLParser, defined in Standard Library
module html.parser. When fed a string containing HTML code, your class should
print the headings, one per line and in the order in which they appear in the
document. Each heading should be indented as follows: an h1 heading should have indentation 0, and h2 heading should have indentation 1, etc. Test your
implementation using w3c.html.
>>> infile = open('w3c.html')
>>> content = infile.read()
>>> infile.close()
>>> hp = HeadingParser()
>>> hp.feed(content)
W3C Mission
Principles

In [58]:
from html.parser import HTMLParser

class HeadingParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.headings = []
        self.current_level = 0

    def handle_starttag(self, tag, attrs):
        if tag.startswith('h') and tag[1].isdigit():
            self.current_level = int(tag[1])

    def handle_data(self, data):
        if self.current_level > 0:
            indentation = ' ' * (self.current_level - 1)
            self.headings.append(f"{indentation}{data.strip()}")

    def handle_endtag(self, tag):
        if tag.startswith('h') and tag[1].isdigit():
            self.current_level = 0

    def print_headings(self):
        for heading in self.headings:
            print(heading)

if __name__ == "__main__":
    file_path = r"C:\Users\user\Downloads\w3c.html"
    with open(file_path, 'r', encoding='utf-8') as infile:
        content = infile.read()
    hp = HeadingParser()
    hp.feed(content)
    hp.print_headings()

W3C Mission
 Principles

# Question 7 
Implement recursive function webdir() that takes as input: a URL (as a string) and
non-negative integers depth and indent. Your function should visit every web
page reachable from the starting URL web page in depth clicks or less, and print
each web page's URL. As shown below, indentation, specified by indent, should
be used to indicate the depth of a URL.
>>>
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html'
, 2, 0)
http://reed.cs.depaul.edu/lperkovic/csc242/test1.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test2.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test3.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html

In [73]:
from html.parser import HTMLParser
from urllib.request import urlopen
from urllib.parse import urljoin

class LinkParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []

    def handle_starttag(self, tag, attrs):
        if tag == 'a':
            for attr in attrs:
                if attr[0] == 'href':
                    self.links.append(attr[1])

def webdir(url, depth, indent):
    if depth < 0:
        return

    print(' ' * indent + url)
    
    try:
        response = urlopen(url)
        content = response.read().decode()
    except Exception as e:
        print(f"{' ' * indent}Error accessing {url}: {e}")
        return

    parser = LinkParser()
    parser.feed(content)

    for link in parser.links:
        full_url = urljoin(url, link)
        webdir(full_url, depth - 1, indent + 1)

if __name__ == "__main__":
    webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html', 2, 0)

http://reed.cs.depaul.edu/lperkovic/csc242/test1.html
Error accessing http://reed.cs.depaul.edu/lperkovic/csc242/test1.html: HTTP Error 404:

# Question 8
Write SQL queries on the below database table that return:
a) All the temperature data.
b) All the cities, but without repetition.
c) All the records for India.
d) All the Fall records.e) The city, country, and season for which the average rainfall is between 200
and 400 millimeters.
f) The city and country for which the average Fall temperature is above 20
degrees, in increasing temperature order.
g) The total annual rainfall for Cairo.
h) The total rainfall for each season.

In [62]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')

create_table_query = '''
CREATE TABLE WeatherData (
    City TEXT,
    Country TEXT,
    Season TEXT,
    "Temperature (C)" REAL,
    "Rainfall (mm)" REAL
);
'''
conn.execute(create_table_query)

data = [
    ('Mumbai', 'India', 'Winter', 24.8, 5.9),
    ('Mumbai', 'India', 'Spring', 28.4, 16.2),
    ('Mumbai', 'India', 'Summer', 27.9, 1549.4),
    ('Mumbai', 'India', 'Fall', 27.6, 346.0),
    ('London', 'United Kingdom', 'Winter', 4.2, 207.7),
    ('London', 'United Kingdom', 'Spring', 8.3, 169.6),
    ('London', 'United Kingdom', 'Summer', 15.7, 157.0),
    ('London', 'United Kingdom', 'Fall', 10.4, 218.5),
    ('Cairo', 'Egypt', 'Winter', 13.6, 16.5),
    ('Cairo', 'Egypt', 'Spring', 20.7, 6.5),
    ('Cairo', 'Egypt', 'Summer', 27.7, 0.1),
    ('Cairo', 'Egypt', 'Fall', 22.2, 4.5),
]
conn.executemany('''
INSERT INTO WeatherData (City, Country, Season, "Temperature (C)", "Rainfall (mm)")
VALUES (?, ?, ?, ?, ?)
''', data)

conn.commit()

temperature_data = pd.read_sql_query('SELECT "Temperature (C)" FROM WeatherData;', conn)
print(temperature_data)

unique_cities = pd.read_sql_query('SELECT DISTINCT City FROM WeatherData;', conn)
print(unique_cities)

india_records = pd.read_sql_query('SELECT * FROM WeatherData WHERE Country = "India";', conn)
print(india_records)

fall_records = pd.read_sql_query('SELECT * FROM WeatherData WHERE Season = "Fall";', conn)
print(fall_records)

average_rainfall = pd.read_sql_query('''
SELECT City, Country, Season 
FROM WeatherData 
GROUP BY City, Country, Season 
HAVING AVG("Rainfall (mm)") BETWEEN 200 AND 400;
''', conn)
print(average_rainfall)

above_20_fall = pd.read_sql_query('''
SELECT City, Country 
FROM WeatherData 
WHERE Season = "Fall" 
GROUP BY City, Country 
HAVING AVG("Temperature (C)") > 20 
ORDER BY AVG("Temperature (C)") ASC;
''', conn)
print(above_20_fall)

total_rainfall_cairo = pd.read_sql_query('''
SELECT SUM("Rainfall (mm)") AS Total_Rainfall 
FROM WeatherData 
WHERE City = "Cairo";
''', conn)
print(total_rainfall_cairo)

total_rainfall_per_season = pd.read_sql_query('''
SELECT Season, SUM("Rainfall (mm)") AS Total_Rainfall 
FROM WeatherData 
GROUP BY Season;
''', conn)
print(total_rainfall_per_season)

conn.close()

    Temperature (C)
0              24.8
1              28.4
2              27.9
3              27.6
4               4.2
5               8.3
6              15.7
7              10.4
8              13.6
9              20.7
10             27.7
11             22.2
     City
0  Mumbai
1  London
2   Cairo
     City Country  Season  Temperature (C)  Rainfall (mm)
0  Mumbai   India  Winter             24.8            5.9
1  Mumbai   India  Spring             28.4           16.2
2  Mumbai   India  Summer             27.9         1549.4
3  Mumbai   India    Fall             27.6          346.0
     City         Country Season  Temperature (C)  Rainfall (mm)
0  Mumbai           India   Fall             27.6          346.0
1  London  United Kingdom   Fall             10.4          218.5
2   Cairo           Egypt   Fall             22.2            4.5
     City         Country  Season
0  London  United Kingdom    Fall
1  London  United Kingdom  Winter
2  Mumbai           India    Fall
     City Country
0   Cairo   Egypt
1  Mumbai   India
   Total_Rainfall
0            27.6
   Season  Total_Rainfall
0    Fall           569.0
1  Spring           192.3
2  Summer          1706.5
3  Winter           230.1

# Question 9

. Suppose list words is defined as follows:| 
>>> words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over',
'the', 'lazy', 'dog']
Write list comprehension expressions that use list words and generate the following
lists:
a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE',
'LAZY', 'DOG']
b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog']
c) [3, 5, 5, 3, 5, 4, 3, 4, 3] (the list of lengths of words in list
words).
d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN',
'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5],
['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy',
4], ['DOG', 'dog', 3]] (the list containing a list for every word of list
words, where each list contains the word in uppercase and lowercase and the
length of the word.)
e) ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog'] (the list of words in list words containing 4 or more
characters.)

In [64]:
words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

uppercase_words = [word.upper() for word in words]
print(uppercase_words)

lowercase_words = [word.lower() for word in words]
print(lowercase_words)

lengths_of_words = [len(word) for word in words]
print(lengths_of_words)

combined_list = [[word.upper(), word.lower(), len(word)] for word in words]
print(combined_list)

words_with_four_or_more = [word for word in words if len(word) >= 4]
print(words_with_four_or_more)

['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE', 'LAZY', 'DOG']
['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
[3, 5, 5, 3, 5, 4, 3, 4, 3]
[['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN', 'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5], ['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy', 4], ['DOG', 'dog', 3]]
['quick', 'brown', 'jumps', 'over', 'lazy']